### ISSUE TITLE
ThaumaticAugmentation makes error during JourneyMap render 

### ISSUE THREAD

**Issue by jonassm** [TheCodex6824/ThaumicAugmentation#159]
Forge: 14.23.5

ThaumAug: 2.0.12

Minecraft: 1.12.2

When i try to automap with JourneyMap, it does not work, and looking at the logs, ThaumAug is causing this error during automap:

```
[13:03:25] [JM-task-4/ERROR] [journeymap]: Unexpected error during RunnableTask: java.lang.UnsupportedOperationException: Can't deserialize non-API implementation (or non-server implementations)
	at thecodex6824.thaumicaugmentation.init.CapabilityHandler$6.readNBT(CapabilityHandler.java:213)
	at thecodex6824.thaumicaugmentation.init.CapabilityHandler$6.readNBT(CapabilityHandler.java:208)
	at net.minecraftforge.common.capabilities.Capability.readNBT(Capability.java:102)
	at thecodex6824.thaumicaugmentation.common.capability.provider.SimpleCapabilityProvider.deserializeNBT(SimpleCapabilityProvider.java:43)
	at thecodex6824.thaumicaugmentation.common.capability.provider.SimpleCapabilityProvider.deserializeNBT(SimpleCapabilityProvider.java:31)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:472)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:61)
	at journeymap.client.io.nbt.ChunkLoader.getChunkMD(ChunkLoader.java:39)
	at journeymap.client.task.multi.MapRegionTask.performTask(MapRegionTask.java:105)
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by TechnoMysterio** [comment]
Make sure Forge, Thaumic Augmentation, JourneyMap and any other mods you might have are all updated, and see that helps at all. If the crash still occurs, then post another log and we can look into it further.

**Comment by Pysis868** [comment]
OS: Windows 10
Java: version 1.8.0_51, vendor Oracle Corporation
JVM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03, mixed mode)
Minecraft: 1.12.2
Minecraft Launcher: 2.2.2529
forge-14.23.5.2854 (latest is forge-14.23.5.2855)
Modpack: MC Eternal 1.4.4.4 (latest)
ThaumicAugmentation-1.12.2-2.0.13 from Dec 25, 2020 (latest)
journeymap-1.12.2-5.7.1 from Mar 29, 2020 (latest for 1.12.2)

[Exception](https://pastebin.com/VJVeJn7E) (The same as above):
```
[00:32:37] [JM-task-7/ERROR]: Unexpected error during RunnableTask: java.lang.UnsupportedOperationException: Can't deserialize non-API implementation (or non-server implementations)
    at thecodex6824.thaumicaugmentation.init.CapabilityHandler$6.readNBT(CapabilityHandler.java:213)
    at thecodex6824.thaumicaugmentation.init.CapabilityHandler$6.readNBT(CapabilityHandler.java:208)
    at net.minecraftforge.common.capabilities.Capability.readNBT(Capability.java:102)
    at thecodex6824.thaumicaugmentation.common.capability.provider.SimpleCapabilityProvider.deserializeNBT(SimpleCapabilityProvider.java:43)
    at thecodex6824.thaumicaugmentation.common.capability.provider.SimpleCapabilityProvider.deserializeNBT(SimpleCapabilityProvider.java:31)
    at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:472)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:61)
    at journeymap.client.io.nbt.ChunkLoader.getChunkMD(ChunkLoader.java:39)
    at journeymap.client.task.multi.MapRegionTask.performTask(MapRegionTask.java:105)
    at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Pysis868** [comment]
Saw some changes on the experimental branch.  Tried compiling myself.

Produced `ThaumicAugmentation-1.12.2-2.1.0` and Journeymap seems to complete its auto-mapping successfully now!

I see log messages like this, where some did not appear before:
```
[15:10:44] [JM-task-4/INFO]: Potential chunks to map in RegionCoord [1,-1]: 24 of 1024
[15:10:44] [JM-task-4/INFO]: Actual chunks mapped in RegionCoord [1,-1]: 24 
[15:10:44] [JM-task-4/INFO]: Memory usage at  8%
[15:10:44] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Auto-mapping surface (90.9%).
[15:10:44] [Client thread/INFO]: JourneyMap: Auto-mapping surface (90.9%).
[15:10:45] [JM-task-4/INFO]: Potential chunks to map in RegionCoord [1,1]: 1 of 1024
[15:10:45] [JM-task-4/INFO]: Actual chunks mapped in RegionCoord [1,1]: 1 
[15:10:45] [JM-task-4/INFO]: Memory usage at  8%
[15:10:45] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Auto-mapping surface (100%).
[15:10:45] [Client thread/INFO]: JourneyMap: Auto-mapping surface (100%).
[15:10:46] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Auto-mapping of surface has stopped.
[15:10:46] [Client thread/INFO]: JourneyMap: Auto-mapping of surface has stopped.
```

Had some build troubles and didn't see any instructions in the README.  Used a command from a post like this one: `env GRADLE_OPTS="-Dfile.encoding=utf-8" ./gradlew build`

All the others dealing with the properties or gradle file were not working, but this one did.

**Comment by TheCodex6824** [comment]
I forgot to tag this issue in the commit but building should now work better for you - I removed the problematic characters from the maze file and tried to specify the encoding as explicitly UTF-8.
