### ISSUE TITLE
IDK what this is, but it IS a ThaumAug error...

### ISSUE THREAD

**Issue by VoxNiphili** [TheCodex6824/ThaumicAugmentation#225]
java.lang.NullPointerException: Unexpected error
20:02:27.797
game
at thecodex6824.thaumicaugmentation.common.block.BlockTASlab$Half$1.func_77667_c(BlockTASlab.java:78)
20:02:27.797
game
at net.silentchaos512.wit.info.ObjectInfo.<init>(ObjectInfo.java:78)
20:02:27.797
game
at net.silentchaos512.wit.info.ItemStackInfo.<init>(ItemStackInfo.java:31)
20:02:27.797
game
at net.silentchaos512.wit.info.BlockStackInfo.<init>(BlockStackInfo.java:43)
20:02:27.797
game
at net.silentchaos512.wit.WIT.getRenderObject(WIT.java:207)
20:02:27.797
game
at net.silentchaos512.wit.WIT.onRenderOverlay(WIT.java:245)
20:02:27.797
game
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1089_WIT_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
20:02:27.797
game
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
20:02:27.797
game
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
20:02:27.797
game
at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
20:02:27.797
game
at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:741)
20:02:27.797
game
at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
20:02:27.797
game
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
20:02:27.797
game
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
20:02:27.797
game
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
20:02:27.797
game
at net.minecraft.client.main.Main.main(SourceFile:123)
20:02:27.797
game
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:02:27.797
game
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:02:27.797
game
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:02:27.797
game
at java.lang.reflect.Method.invoke(Method.java:497)
20:02:27.797
game
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
20:02:27.797
game
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheCodex6824** [comment]
Your "WIT" mod seems to assume that all blockstate metadata combinations are applicable to items, which is false. I'll add a check in to prevent the game from crashing if this happens, but the variant of slab that mod thinks it is will probably be wrong.

**Comment by VoxNiphili** [comment]
ah, that's good. The "WIT" mod is "What Is That", I think
