### ISSUE TITLE
Integration with Electroblob Wizardry makes the game crash

### ISSUE THREAD

**Issue by fmichaut-dev** [TheCodex6824/ThaumicAugmentation#289]
Every night that I go out and try to fight back the skeletons and others monsters the game crashes.

Here is the crash report : 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  wings (wings-1.1.5-1.12.2.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  AALoadingPlugin (arcanearchives-0.2.0.1.jar)
  Incorporeal Tweaker (incorporeal-1.1.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  Persistency (persistency-1.2.0.jar)
  Quark Plugin (Quark-r1.6-174.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.10-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  MixinBooter (!mixinbooter-4.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  Botania Tweaks Core (botaniatweaks-1.8.6.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 5/23/22 1:59 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: electroblob/wizardry/entity/projectile/EntityMagicFireball
	at thecodex6824.thaumicaugmentation.common.integration.IntegrationEBWizardry.onDamage(IntegrationEBWizardry.java:47)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler.lambda$null$0(PlayerEventHandler.java:99)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler$$Lambda$5158/894942126.accept(Unknown Source)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler.invoke(PlayerEventHandler.java:94)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler.lambda$static$1(PlayerEventHandler.java:98)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler$$Lambda$4671/1941286109.accept(Unknown Source)
	at thecodex6824.thaumicaugmentation.common.event.PlayerEventHandler.onDamage(PlayerEventHandler.java:391)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1065_PlayerEventHandler_onDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:609)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369)
	at com.bewitchment.common.entity.misc.ModEntityTippedArrow.func_184549_a(ModEntityTippedArrow.java:38)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
...

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1181245024 bytes (1126 MB) / 3197108224 bytes (3049 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 190 mods loaded, 189 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                  | Source                                                   | Signature                                |
	|:------ |:------------------------- |:------------------------ |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                   | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                       | 9.42                     | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | incorporeal_core          | 1.1.0                    | minecraft.jar                                            | None                                     |
	| LCHIJA | persistency               | 1.2.0                    | minecraft.jar                                            | None                                     |
	| LCHIJA | mixinbooter               | 4.2                      | minecraft.jar                                            | None                                     |
	| LCHIJA | foamfixcore               | 7.7.4                    | minecraft.jar                                            | None                                     |
	| LCHIJA | botania_tweaks_core       | -100                     | minecraft.jar                                            | None                                     |
	| LCHIJA | ctm                       | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                                | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                     | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                                 | None                                     |
	| LCHIJA | mysticalmechanics         | 0.10                     | Mystical Mechanics-0.10.jar                              | None                                     |
	| LCHIJA | embers                    | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                         | None                                     |
	| LCHIJA | aetherworks               | 1.12.2-1.0.0.3           | AetherWorks-1.12.2-1.0.0.3.jar                           | None                                     |
	| LCHIJA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia                  | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar                   | None                                     |
	| LCHIJA | placebo                   | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                                 | None                                     |
	| LCHIJA | singularities             | 2.4.1                    | Singularities-1.12.2-2.4.1.jar                           | None                                     |
	| LCHIJA | crafttweaker              | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                            | None                                     |
	| LCHIJA | mtlib                     | 3.0.6                    | MTLib-3.0.6.jar                                          | None                                     |
	| LCHIJA | modtweaker                | 4.0.17                   | modtweaker-4.0.17.jar                                    | None                                     |
	| LCHIJA | jei                       | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                                | None                                     |
	| LCHIJA | projecte                  | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                              | None                                     |
	| LCHIJA | chisel                    | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                             | None                                     |
	| LCHIJA | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None                                     |
	| LCHIJA | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar              | None                                     |
	| LCHIJA | tconstruct                | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                         | None                                     |
	| LCHIJA | p455w0rdslib              | 2.2.156                  | p455w0rdslib-1.12.2-2.2.156.jar                          | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                  | 1.0.30                   | AE2WTLib-1.12.2-1.0.30.jar                               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | akashictome               | 1.2-12                   | AkashicTome-1.2-12.jar                                   | None                                     |
	| LCHIJA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                               | None                                     |
	| LCHIJA | gbook_snapshot            | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                            | None                                     |
	| LCHIJA | arcanearchives            | 0.2.0.1                  | arcanearchives-0.2.0.1.jar                               | None                                     |
	| LCHIJA | astralsorcery             | 1.10.19                  | astralsorcery-1.12.2-1.10.19.jar                         | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | attributefix              | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | quark                     | r1.6-174                 | Quark-r1.6-174.jar                                       | None                                     |
	| LCHIJA | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                                    | None                                     |
	| LCHIJA | botania_tweaks            | 1.8.6                    | botaniatweaks-1.8.6.jar                                  | None                                     |
	| LCHIJA | botania                   | r1.10-361                | Botania r1.10-361.jar                                    | None                                     |
	| LCHIJA | avaritiatweaks            | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                            | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar              | None                                     |
	| LCHIJA | base                      | 3.13.0                   | base-1.12.2-3.13.0.jar                                   | None                                     |
	| LCHIJA | bhc                       | 2.0.3                    | baubley-heart-canisters-1.12.2-2.0.3.jar                 | None                                     |
	| LCHIJA | betterbedrockgen          | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar                    | None                                     |
	| LCHIJA | betterbuilderswands       | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar        | None                                     |
	| LCHIJA | patchouli                 | 1.0-20                   | Patchouli-1.0-20.jar                                     | None                                     |
	| LCHIJA | bewitchment               | 0.20.6                   | bewitchment-1.12.2-0.0.20.6.jar                          | None                                     |
	| LCHIJA | birdsfoods                | 3.1 - [1.12]             | birdsfoods-1.12 - 3.1.jar                                | None                                     |
	| LCHIJA | blockcraftery             | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                           | None                                     |
	| LCHIJA | guideapi                  | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                              | None                                     |
	| LCHIJA | bloodmagic                | 1.12.2-2.4.1-103         | BloodMagic-1.12.2-2.4.1-103.jar                          | None                                     |
	| LCHIJA | bloodarsenal              | 1.12.2-2.2.0-28          | BloodArsenal-1.12.2-2.2.0-28.jar                         | None                                     |
	| LCHIJA | bookshelf                 | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | nibbler                   | 0.4.1                    | nibbler-1.12.2-0.4.1.jar                                 | None                                     |
	| LCHIJA | botaunomy                 | 0.2.1                    | botaunomy-1.12.2-0.2.1.jar                               | None                                     |
	| LCHIJA | buildinggadgets           | 2.7.1                    | BuildingGadgets-2.7.1.jar                                | None                                     |
	| LCHIJA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                                 | None                                     |
	| LCHIJA | chesttransporter          | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                        | None                                     |
	| LCHIJA | chiselsandbits            | 14.33                    | chiselsandbits-14.33.jar                                 | None                                     |
	| LCHIJA | clumps                    | 3.1.2                    | Clumps-3.1.2.jar                                         | None                                     |
	| LCHIJA | cyclopscore               | 1.5.0                    | CyclopsCore-1.12.2-1.5.0.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities        | 2.4.4                    | CommonCapabilities-1.12.2-2.4.4.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | contenttweaker            | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                          | None                                     |
	| LCHIJA | conarm                    | 1.2.4                    | conarm-1.12.2-1.2.4.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | controlling               | 3.0.7                    | Controlling-3.0.7.jar                                    | None                                     |
	| LCHIJA | craftingtweaks            | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                          | None                                     |
	| LCHIJA | craftpresence             | v1.5.5                   | CraftPresence-1.12.2-1.5.5.jar                           | eca02c6a597321ad22340897683951ba5c76720a |
	| LCHIJA | craftstudioapi            | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar       | None                                     |
	| LCHIJA | ctgui                     | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                            | None                                     |
	| LCHIJA | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                            | None                                     |
	| LCHIJA | cucumber                  | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                                | None                                     |
	| LCHIJA | custommainmenu            | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                        | None                                     |
	| LCHIJA | darkutils                 | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | discordsuite              | 2.2.4                    | DiscordSuite-2.2.4.jar                                   | None                                     |
	| LCHIJA | dragonmounts              | 1.12.2-1.6.3             | DragonMounts2-1.12.2-1.6.3.jar                           | None                                     |
	| LCHIJA | eerieentities             | 1.0.7                    | EerieEntities-1.12.2-1.0.7.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ebwizardry                | 4.1.4                    | Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar           | None                                     |
	| LCHIJA | emberroot                 | 1.3.9                    | EmberRootZoo-1.12.2-1.3.10.jar                           | None                                     |
	| LCHIJA | embersified               | 1.0.3                    | Embersified-1.12.2-1.0.3.jar                             | None                                     |
	| LCHIJA | emberstic                 | 0.1.0                    | emberstic-0.1.0.jar                                      | None                                     |
	| LCHIJA | eplus                     | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | equivalentenergistics     | 0.8.3                    | EquivalentEnergistics-1.12.2-PE_1.3.1B-AE2_RV6-0.8.3.jar | None                                     |
	| LCHIJA | evilcraft                 | 0.10.77                  | EvilCraft-1.12.2-0.10.77.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat           | 1.0.0                    | EvilCraft-1.12.2-0.10.77.jar                             | None                                     |
	| LCHIJA | hammercore                | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | expequiv                  | 12r                      | ExpandedEquivalence-1.12.2-12r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | theoneprobe               | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                              | None                                     |
	| LCHIJA | extrabotany               | 55                       | ExtraBotany-r1.1-55-fixed.jar                            | None                                     |
	| LCHIJA | fastfurnace               | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                             | None                                     |
	| LCHIJA | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | fastbench                 | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                           | None                                     |
	| LCHIJA | fencejumper               | 1.0.5                    | fencejumper-1.12-1.0.5.jar                               | None                                     |
	| LCHIJA | foamfix                   | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                                | None                                     |
	| LCHIJA | forgelin                  | 1.8.3                    | Forgelin-1.8.3.jar                                       | None                                     |
	| LCHIJA | ftblib                    | 5.4.3.130                | FTBLib-5.4.3.130.jar                                     | None                                     |
	| LCHIJA | ftbutilities              | 5.4.0.100                | FTBUtilities-5.4.0.100.jar                               | None                                     |
	| LCHIJA | itemfilters               | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                                 | None                                     |
	| LCHIJA | ftbquests                 | 1.7.2.189                | FTBQuests-1.7.2.189.jar                                  | None                                     |
	| LCHIJA | ftbbackups                | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar                          | None                                     |
	| LCHIJA | limelib                   | 1.7.12                   | limelib-1.12.2-1.7.12.jar                                | None                                     |
	| LCHIJA | furnus                    | 2.1.8                    | furnus-1.12.2-2.1.8.jar                                  | None                                     |
	| LCHIJA | harvest                   | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                                | None                                     |
	| LCHIJA | incorporeal               | 1.1.4                    | incorporeal-1.1.4.jar                                    | None                                     |
	| LCHIJA | initialinventory          | 2.0.2                    | InitialInventory-3.0.0.jar                               | None                                     |
	| LCHIJA | integrateddynamics        | 1.0.18                   | IntegratedDynamics-1.12.2-1.0.18.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integrateddynamicscompat  | 1.0.0                    | IntegratedDynamics-1.12.2-1.0.18.jar                     | None                                     |
	| LCHIJA | integratedtunnels         | 1.6.10                   | IntegratedTunnels-1.12.2-1.6.10.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integratedtunnelscompat   | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.10.jar                      | None                                     |
	| LCHIJA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jee                       | 1.0.7                    | JustEnoughEnergistics-1.12.2-1.0.7.jar                   | None                                     |
	| LCHIJA | jeresources               | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar                  | None                                     |
	| LCHIJA | kjlib                     | 1.0.4                    | kjlib-1.0.4.jar                                          | None                                     |
	| LCHIJA | shotgunsandglitter        | 1.6                      | shotgunsandglitter-1.6.jar                               | None                                     |
	| LCHIJA | librarianlib              | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar                   | None                                     |
	| LCHIJA | psi                       | r1.1-77                  | Psi-r1.1-77.jar                                          | None                                     |
	| LCHIJA | magipsi                   | 1.3                      | MagicalPsi-1.3.2.jar                                     | None                                     |
	| LCHIJA | mysticalagriculture       | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar                     | None                                     |
	| LCHIJA | matc                      | 1.0.1-hotfix             | matc-1.0.1-hotfix.jar                                    | None                                     |
	| LCHIJA | mcjtylib_ng               | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                                  | None                                     |
	| LCHIJA | tbone                     | v1.6.8+mc1.12.2          | TBone-v1.6.8+mc1.12.2.jar                                | None                                     |
	| LCHIJA | metalchests               | v6.1.0+mc1.12.2          | MetalChests-v6.1.0+mc1.12.2.jar                          | None                                     |
	| LCHIJA | minicoal                  | 1.0                      | minicoal-1.12.2-1.0.jar                                  | None                                     |
	| LCHIJA | mist                      | alpha_c_09               | MistWorld_1.12.2_alpha_c_09.jar                          | None                                     |
	| LCHIJA | testdummy                 | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                               | None                                     |
	| LCHIJA | modnametooltip            | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                         | None                                     |
	| LCHIJA | moreoverlays              | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                         | None                                     |
	| LCHIJA | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                              | None                                     |
	| LCHIJA | mousetweaks               | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                            | None                                     |
	| LCHIJA | llibrary                  | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs               | 1.5.4                    | mowziesmobs-1.5.4.jar                                    | None                                     |
	| LCHIJA | multimob                  | 1.0.5                    | multimob-1.0.5.jar                                       | None                                     |
	| LCHIJA | mystcraft                 | 0.13.7.04                | mystcraft-1.12.2-0.13.7.04.jar                           | None                                     |
	| LCHIJA | mysticalagradditions      | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar                    | None                                     |
	| LCHIJA | mysticalwildlife          | 1.3.0                    | mysticalwildlife-1.12.2-1.3.0.jar                        | None                                     |
	| LCHIJA | mysticalworld             | 1.12.2-1.3.2             | MysticWorld-1.12.2-1.3.2.jar                             | None                                     |
	| LCHIJA | naturalpledge             | 3.0.3                    | NaturalPledge-r3.1.2.jar                                 | None                                     |
	| LCHIJA | naturesaura               | r17                      | NaturesAura-r17.jar                                      | None                                     |
	| LCHIJA | naturescompass            | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                          | None                                     |
	| LCHIJA | netherchest               | 1.1.1                    | netherchest-1.1.1.jar                                    | None                                     |
	| LCHIJA | norecipebook              | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                       | None                                     |
	| LCHIJA | oreexcavation             | 1.4.140                  | OreExcavation-1.4.140.jar                                | None                                     |
	| LCHIJA | oeintegration             | 2.3.4                    | oeintegration-2.3.4.jar                                  | None                                     |
	| LCHIJA | soot                      | 1.6                      | Soot-1.6.jar                                             | None                                     |
	| LCHIJA | thebetweenlands           | 3.4.10                   | TheBetweenlands-3.4.10-universal.jar                     | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | pewter                    | 1.4.3                    | Pewter-1.4.3.jar                                         | None                                     |
	| LCHIJA | primitivemobs             | 1.2.3a                   | primitivemobs-1.2.3a.jar                                 | None                                     |
	| LCHIJA | quarkoddities             | 1                        | QuarkOddities-1.12.2.jar                                 | None                                     |
	| LCHIJA | rangedpumps               | 0.5                      | rangedpumps-0.5.jar                                      | None                                     |
	| LCHIJA | refinedstorage            | 1.6.15                   | refinedstorage-1.6.15.jar                                | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | refinedexchange           | 2.1.1                    | refinedexchange-2.1.1.jar                                | None                                     |
	| LCHIJA | refinedstorageaddons      | 0.4.4                    | refinedstorageaddons-0.4.4.jar                           | None                                     |
	| LCHIJA | refinedstoragerequestify  | ${version}               | refinedstoragerequestify-1.12.2-1.0.2-3.jar              | None                                     |
	| LCHIJA | xreliquary                | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                           | None                                     |
	| LCHIJA | resourceloader            | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | rockcandy                 | 1.12.2-3.00              | rockcandy-1.12.2-3.0.0.jar                               | None                                     |
	| LCHIJA | rootsclassic              | 1.12.2-1.1.5             | RootsClassic-1.12.2-1.1.5.jar                            | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | rustic                    | 1.1.1                    | rustic-1.1.1.jar                                         | None                                     |
	| LCHIJA | rusticthaumaturgy         | 4.4a                     | Rustic Thaumaturgy-4.4a.jar                              | None                                     |
	| LCHIJA | soulshardsrespawn         | 1.12.2-1.1.1-13          | SoulShardsRespawn-1.12.2-1.1.1-13.jar                    | None                                     |
	| LCHIJA | sct                       | 1.0.3                    | StoneCraftingTable-1.12.2-1.0.3.jar                      | None                                     |
	| LCHIJA | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                          | None                                     |
	| LCHIJA | tammodized                | 0.15.6                   | TamModized-1.12.2-0.15.6.jar                             | None                                     |
	| LCHIJA | thaumicaugmentation       | 1.12.2-2.1.5             | ThaumicAugmentation-1.12.2-2.1.5.jar                     | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | thaumicjei                | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                           | None                                     |
	| LCHIJA | thaumicenergistics        | 2.2.3                    | thaumicenergistics-2.2.3.jar                             | None                                     |
	| LCHIJA | thaumicequivalence        | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar                      | None                                     |
	| LCHIJA | thaumicgrid               | 1.0.12                   | ThaumicGrid-1.0.12.jar                                   | None                                     |
	| LCHIJA | tcinventoryscan           | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar               | None                                     |
	| LCHIJA | thaumicperiphery          | 0.3.0                    | thaumicperiphery-0.3.0.jar                               | None                                     |
	| LCHIJA | thaumicspeedup            | 4.0                      | thaumicspeedup-4.0.jar                                   | None                                     |
	| LCHIJA | tinkersjei                | 1.2                      | tinkersjei-1.2.jar                                       | None                                     |
	| LCHIJA | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                      | None                                     |
	| LCHIJA | tombstone                 | 3.5.5                    | tombstone-3.5.5-1.12.jar                                 | None                                     |
	| LCHIJA | topaddons                 | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                              | None                                     |
	| LCHIJA | traverse                  | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                             | None                                     |
	| LCHIJA | v0idssmartbackpacks       | 1.0.6                    | V0id's Smart Backpacks-1.0.6.jar                         | None                                     |
	| LCHIJA | voidcraft                 | 0.26.10                  | VoidCraft-1.12-0.26.10.jar                               | None                                     |
	| LCHIJA | waystones                 | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                              | None                                     |
	| LCHIJA | wings                     | 1.1.5                    | wings-1.1.5-1.12.2.jar                                   | None                                     |
	| LCHIJA | bauble_wings              | 1.0.0                    | wings-1.1.5-1.12.2.jar                                   | None                                     |
	| LCHIJA | wct                       | 3.12.93                  | WirelessCraftingTerminal-1.12.2-3.12.93.jar              | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | wizardry                  | 0.10.8                   | wizardry-0.10.8.jar                                      | None                                     |
	| LCHIJA | xaerominimap              | 1.17.4                   | Xaeros_Minimap_1.17.4_Forge_1.12.jar                     | None                                     |
	| LCHIJA | reauth                    | 3.6.0                    | reauth-3.6.0.jar                                         | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | librarianliblate          | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar                   | None                                     |
	| LCHIJA | mysticallib               | 1.12.2-1.3.1             | mysticallib-1.12.2-1.3.1.jar                             | None                                     |
	| UD     | mobends_wings             | 1.0.0                    | wings-1.1.5-1.12.2.jar                                   | None                                     |

```

**Comment by TheCodex6824** [comment]
The version of EB Wizardry you're using is quite old, so it's missing the thing I was checking for. I suggest updating it if you can, but otherwise I'll at least make the game stop crashing.

**Comment by fmichaut-dev** [comment]
Yeah I guess I am using an old modpack... 
I've tried adding ThaumicAugmentation in it because I was missing all the amzing stuff you made, but I dit not think much about mods versions 

Thanks for the fix !
