### ISSUE TITLE
Server dont start

### ISSUE THREAD

**Issue by fishfuture** [TheCodex6824/ThaumicAugmentation#307]
I got the following error when I started using this mod
The server core is cateserver:https://github.com/Luohuayu/CatServer
[LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [CatServer.jar:git-CatServer-1.12.2-8d58cdb8]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [CatServer.jar:git-CatServer-1.12.2-8d58cdb8]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at catserver.server.CatServerLaunch.main(CatServerLaunch.java:17) [CatServer.jar:git-CatServer-1.12.2-8d58cdb8]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayer.func_71059_n(Lnet/minecraft/entity/Entity;)V @1331: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[3]) is not assignable to 'net/minecraft/entity/Entity'
  Current Frame:
    bci: @1331
    flags: { }
    locals: { 'net/minecraft/entity/player/EntityPlayer', 'net/minecraft/entity/Entity', float, float, float, integer, integer, integer, integer, 'net/minecraftforge/event/entity/player/CriticalHitEvent', integer, double, double_2nd, float, integer, integer, top, double, double_2nd, double, double_2nd, double, double_2nd, integer, 'net/minecraft/item/ItemStack', 'java/lang/Object', float }
    stack: { uninitialized 1321, uninitialized 1321, 'org/bukkit/craftbukkit/v1_12_R1/entity/CraftHumanEntity', 'java/lang/Object' }
  Bytecode:
    0x0000000: 2a2b b807 439a 0004 b12b b607 4699 05ef
    0x0000010: 2b2a b607 499a 05e7 2ab2 015d b601 6fb9
    0x0000020: 0314 0100 9045 2bc1 0004 9900 152a b602
    0x0000030: 1f2b c000 04b6 074d b807 5146 a700 0e2a
    0x0000040: b602 1fb2 0757 b807 5146 2a13 0362 b607
    0x0000050: 5a38 0424 1302 5217 0417 046a 1303 356a
    0x0000060: 626a 4525 1704 6a46 2ab6 0229 240b 959d
    0x0000070: 0009 250b 959e 0587 1704 1307 5b95 9e00
    0x0000080: 0704 a700 0403 3605 0336 0603 3607 1507
    0x0000090: 2ab8 075e 6036 072a b603 0e99 002e 1505
    0x00000a0: 9900 292a b401 c301 c000 022a b402 042a
    0x00000b0: b402 142a b402 11b2 0761 2ab6 028f 0c0c
    0x00000c0: b602 9384 0701 0436 0615 0599 003d 2ab4
    0x00000d0: 0361 0b95 9e00 342a b401 b99a 002d 2ab6
    0x00000e0: 0764 9a00 262a b603 659a 001f 2ab2 0767
    0x00000f0: b604 fa9a 0015 2ab6 02a5 9a00 0e2b c100
    0x0000100: 0499 0007 04a7 0004 0336 0815 0899 000e
    0x0000110: 2ab6 030e 9a00 0704 a700 0403 3608 2a2b
    0x0000120: 1508 1508 9900 0913 0768 a700 040c b807
    0x0000130: 6c3a 0919 09c6 0007 04a7 0004 0336 0815
    0x0000140: 0899 000b 2419 09b6 0771 6a45 2425 6245
    0x0000150: 0336 0a2a b407 742a b407 7766 8d39 0b15
    0x0000160: 0599 003f 1508 9a00 3a15 069a 0035 2ab4
    0x0000170: 01b9 9900 2e18 0b2a b607 7a8d 989c 0023
    0x0000180: 2ab2 06b9 b607 1e3a 0d2a 190d b807 809a
    0x0000190: 000e 190d b604 2ec1 0782 9900 0604 360a
    0x00001a0: 0b38 0d03 360e 2ab8 0785 360f 2bc1 0004
    0x00001b0: 9900 482b c000 04b6 0786 380d 150f 9e00
    0x00001c0: 3a2b b607 879a 0033 bb07 8959 2ab6 0474
    0x00001d0: 2bb6 078c 04b7 078f 3a10 b807 9219 10b9
    0x00001e0: 0490 0200 1910 b607 939a 000f 0436 0e2b
    0x00001f0: 1910 b607 96b6 0799 2bb4 079a 3911 2bb4
    0x0000200: 079b 3913 2bb4 079c 3915 2b2a b807 a024
    0x0000210: b607 a136 1715 1799 03a9 1507 9e00 822b
    0x0000220: c100 0499 002e 2bc0 0004 2a15 0786 1303
    0x0000230: 626a 2ab4 02af 1303 e86a b803 ef8d 2ab4
    0x0000240: 02af 1303 e86a b803 ec76 8db6 07a5 a700
    0x0000250: 332b 2ab4 02af 1303 e86a b803 ef76 1507
    0x0000260: 866a 1303 626a 8d14 07a6 2ab4 02af 1303
    0x0000270: e86a b803 ec15 0786 6a13 0362 6a8d b607
    0x0000280: aa2a 59b4 031b 1407 ab6b b503 1b2a 59b4
    0x0000290: 031e 1407 ab6b b503 1e2a 03b6 07af 150a
    0x00002a0: 9900 bb0c 2ab8 07b3 246a 6238 182a b401
    0x00002b0: c312 042b b603 3b0f 1402 4a0f b603 43b6
    0x00002c0: 07b7 b907 b801 003a 1919 19b9 0600 0100
    0x00002d0: 9900 6719 19b9 0604 0100 c000 043a 1a19
    0x00002e0: 1a2a a500 5219 1a2b a500 4c2a 191a b607
    0x00002f0: bb9a 0043 2a19 1ab6 07bf 1407 c098 9c00
    0x0000300: 3619 1a2a b807 a0b6 07c5 1718 b606 5199
    0x0000310: 0025 191a 2a13 0331 2ab4 02af 1303 e86a
    0x0000320: b803 ef8d 2ab4 02af 1303 e86a b803 ec76
    0x0000330: 8db6 07a5 a7ff 952a b401 c301 c000 022a
    0x0000340: b402 042a b402 142a b402 11b2 07c8 2ab6
    0x0000350: 028f 0c0c b602 932a b607 cb2b c100 1999
    0x0000360: 009d 2bb4 07ce 9900 9603 3618 2bb6 078c
    0x0000370: c004 763a 19bb 07d0 5918 1118 1318 15b7
    0x0000380: 07d2 3a1a bb07 d459 1919 191a b607 d8b7
    0x0000390: 07db 3a1b 2ab4 01c3 b604 7cb6 048a 191b
    0x00003a0: b904 9002 0019 1bb6 07dc 9900 0904 3618
    0x00003b0: a700 1c19 1a19 1bb6 07df b607 e09a 000f
    0x00003c0: 1919 191b b607 dfb9 07e4 0200 1518 9a00
    0x00003d0: 2e2b c000 19b9 07e8 0100 bb07 ea59 2bb7
    0x00003e0: 07eb b607 f12b 03b5 07ce 2b18 11b5 079a
    0x00003f0: 2b18 13b5 079b 2b18 15b5 079c 1508 9900
    0x0000400: 282a b401 c301 c000 022a b402 042a b402
    0x0000410: 142a b402 11b2 07f4 2ab6 028f 0c0c b602
    0x0000420: 932a 2bb6 07f7 1508 9a00 5015 0a9a 004b
    0x0000430: 1505 9900 262a b401 c301 c000 022a b402
    0x0000440: 042a b402 142a b402 11b2 07fa 2ab6 028f
    0x0000450: 0c0c b602 93a7 0023 2ab4 01c3 01c0 0002
    0x0000460: 2ab4 0204 2ab4 0214 2ab4 0211 b207 fd2a
    0x0000470: b602 8f0c 0cb6 0293 250b 959e 0008 2a2b
    0x0000480: b608 002a 2bb6 0803 2bc1 0004 9900 0b2b
    0x0000490: c000 042a b808 072a 2bb8 080a 2ab6 021f
    0x00004a0: 3a18 2b3a 192b c108 0c99 001b 2bc0 080c
    0x00004b0: b408 103a 1a19 1ac1 0004 9900 0a19 1ac0
    0x00004c0: 0004 3a19 1918 b602 2c9a 0038 1919 c100
    0x00004d0: 0499 0030 1918 b602 2f3a 1a19 1819 19c0
    0x00004e0: 0004 2ab6 0814 1918 b602 2c99 0016 2a19
    0x00004f0: 1ab2 06b9 b806 b32a b206 b9b2 00d2 b607
    0x0000500: 332b c100 0499 00a3 170d 2bc0 0004 b607
    0x0000510: 8666 381a 2ab2 0817 171a 1308 186a b808
    0x0000520: 1bb6 04c3 150f 9e00 35bb 0789 592a b604
    0x0000530: 7419 19b6 078c 150f 0768 b707 8f3a 1bb8
    0x0000540: 0792 191b b904 9002 0019 1bb6 0793 9a00
    0x0000550: 0d19 1919 1bb6 0796 b607 992a b401 c3c1
    0x0000560: 081d 9900 4617 1a0d 959e 003f 171a 8d14
    0x0000570: 0123 6b8e 361b 2ab4 01c3 c008 1db2 0823
    0x0000580: 2bb4 0824 2bb4 0825 2bb4 0826 1303 626a
    0x0000590: 8d63 2bb4 0827 151b 1407 a60e 1407 a614
    0x00005a0: 0828 03bc 0ab6 082d 2a13 06dd b606 e32a
    0x00005b0: 2ab4 01c3 b408 31b4 0836 b606 e3a7 003f
    0x00005c0: 2ab4 01c3 01c0 0002 2ab4 0204 2ab4 0214
    0x00005d0: 2ab4 0211 b208 392a b602 8f0c 0cb6 0293
    0x00005e0: 150e 9900 072b b608 3a2a c100 1999 000f
    0x00005f0: 2ac0 0019 b906 6901 00b6 083d b1       
  Stackmap Table:
    same_frame(@9)
    append_frame(@63,Float)
    append_frame(@74,Float)
    append_frame(@120,Float)
    same_frame(@133)
    same_locals_1_stack_item_frame(@134,Integer)
    append_frame(@201,Integer,Integer,Integer)
    same_frame(@264)
    same_locals_1_stack_item_frame(@265,Integer)
    append_frame(@283,Integer)
    same_locals_1_stack_item_frame(@284,Integer)
    full_frame(@301,{Object[#2],Object[#823],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#823],Integer})
    full_frame(@302,{Object[#2],Object[#823],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#823],Integer,Float})
    append_frame(@316,Object[#1902])
    same_locals_1_stack_item_frame(@317,Integer)
    same_frame(@332)
    append_frame(@413,Integer,Double,Object[#207])
    chop_frame(@416,1)
    append_frame(@504,Float,Integer,Integer)
    full_frame(@593,{Object[#2],Object[#823],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1902],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@641)
    same_frame(@670)
    append_frame(@713,Float,Object[#1533])
    append_frame(@820,Object[#4])
    chop_frame(@823,1)
    chop_frame(@859,2)
    full_frame(@947,{Object[#2],Object[#823],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1902],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer,Integer,Object[#1142],Object[#2000],Object[#2004]},{})
    same_frame(@972)
    full_frame(@1020,{Object[#2],Object[#823],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1902],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@1062)
    same_frame(@1112)
    same_frame(@1144)
    same_frame(@1155)
    same_frame(@1175)
    append_frame(@1220,Object[#207],Object[#1686])
    same_frame(@1281)
    append_frame(@1371,Float)
    chop_frame(@1448,1)
    chop_frame(@1472,2)
    same_frame(@1513)
    full_frame(@1532,{Object[#2],Object[#823]},{})

	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(DataFixesManager.java:170) ~[rz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1722) ~[MinecraftServer.class:?]
	... 17 more

**Comment by TheCodex6824** [comment]
This is an incompatibility with CatServer, until I get around to fixing it properly add `thecodex6824.thaumicaugmentation.core.transformer.TransformerSweepingEdgeCheck` to the `DisabledTransformers` config option (under general)
