### ISSUE TITLE
Incompatible with Botania

### ISSUE THREAD

**Issue by Taskeren** [TheCodex6824/ThaumicAugmentation#315]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PatcherPlugin (AdvSolarPatch-1.2.1.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  PhosphorFMLLoadingPlugin ([磷] phosphor-forge-mc1.12.2-0.2.7-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 22-9-14 上午2:13
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: thecodex6824/thaumicaugmentation/common/item/ItemThaumostaticHarness
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: thecodex6824/thaumicaugmentation/common/item/ItemThaumostaticHarness
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:84)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 31 more
Caused by: java.lang.ClassNotFoundException: thecodex6824.thaumicaugmentation.common.item.ItemThaumostaticHarness
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/api/item/IPhantomInkable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.item.IPhantomInkable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 43 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_312, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 654675472 bytes (624 MB) / 1037959168 bytes (989 MB) up to 12364808192 bytes (11792 MB)
	JVM Flags: 4 total; -Xincgc -XX:+UseCompressedOops -Xms1024M -Xmx12000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.Bukkit.getName(Bukkit.java:92)
	at org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:20)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:41)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:722)
	at java.lang.Thread.run(Thread.java:748)

	FML: MCP 9.42 Powered by Forge 14.23.5.2860 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version            | Source                                                 | Signature                                |
	|:----- |:--------------------- |:------------------ |:------------------------------------------------------ |:---------------------------------------- |
	| LC    | minecraft             | 1.12.2             | minecraft.jar                                          | None                                     |
	| LC    | mcp                   | 9.42               | minecraft.jar                                          | None                                     |
	| LC    | FML                   | 8.0.99.99          | mc.jar                                                 | None                                     |
	| LC    | forge                 | 14.23.5.2860       | mc.jar                                                 | None                                     |
	| LC    | advsolarpatch         | 1.2.1              | minecraft.jar                                          | None                                     |
	| LC    | jei                   | 4.16.1.302         | [JEI物品管理器] jei_1.12.2-4.16.1.302.jar                   | None                                     |
	| LC    | ic2                   | 2.8.222-ex112      | [工业时代2] industrialcraft-2-2.8.222-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | flammpfeil.slashblade | mc1.12-r33         | [拔刀剑] SlashBlade-mc1.12-r33.jar                        | None                                     |
	| LC    | baubles               | 1.5.2              | [饰品栏] Baubles-1.12-1.5.2.jar                           | None                                     |
	| LC    | thaumcraft            | 6.1.BETA26         | [神秘时代] Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LC    | jrftl                 | 1.1                | [腐肉换皮革] JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| LC    | appleskin             | 1.0.14             | [苹果皮] AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LC    | biomesoplenty         | 7.0.1.2445         | [超多生物群系] BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LC    | veinminer             | 0.38.2             | [连锁采矿／矿脉矿工] VeinMiner-1.12-0.38.2.647+b31535a.jar      | None                                     |
	| LC    | veinminermodsupport   | 0.38.2             | [连锁采矿／矿脉矿工] VeinMiner-1.12-0.38.2.647+b31535a.jar      | None                                     |
	| LC    | iridiumsource         | 2.0.1 - MC 1.12.2  | [铱矿产] iridiumsource-2.0.1.jar                          | None                                     |
	| LC    | advanced_solar_panels | 4.3.0              | [高级太阳能] Advanced Solar Panels-4.3.0.jar                | None                                     |
	| LC    | appliedenergistics2   | rv6-stable-7       | appliedenergistics2-rv6-stable-7.jar                   | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | bdlib                 | 1.14.3.12          | bdlib-1.14.3.12-mc1.12.2.jar                           | None                                     |
	| LC    | ae2stuff              | 0.7.0.4            | ae2stuff-0.7.0.4-mc1.12.2.jar                          | None                                     |
	| LC    | creeperconfetti       | 1.4.2              | creeperconfetti-1.4.2.jar                              | None                                     |
	| LC    | forgelin              | 1.8.4              | Forgelin-1.8.4.jar                                     | None                                     |
	| LC    | waila                 | 1.8.26             | Hwyla-1.8.26-B41_1.12.2.jar                            | None                                     |
	| LC    | libnine               | 1.2.1              | libnine-1.12.2-1.2.1.jar                               | None                                     |
	| LC    | threng                | 1.1.26             | lazy-ae2-1.12.2-1.1.26.jar                             | None                                     |
	| LE    | thaumicaugmentation   | 1.12.2-2.1.7       | ThaumicAugmentation-1.12.2-2.1.7.jar                   | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| L     | ironchest             | 1.12.2-7.0.67.844  | 更多箱子.jar                                               | None                                     |
	| L     | botania               | r1.10-364          | 植物魔法.jar                                               | None                                     |
	| L     | thaumicwonders        | 1.8.2              | 神秘奇境.jar                                               | None                                     |
	| L     | thaumictinkerer       | 1.12.2-5.0-353c71c | 神秘工匠.jar                                               | None                                     |
	| L     | guideapi              | 1.12-2.1.8-63      | 血魔法前置mod.jar                                           | None                                     |
	| L     | bloodmagic            | 1.12.2-2.4.3-105   | 血魔法2.jar                                               | None                                     |
	| L     | extrabotany           | 58                 | 额外植物学.jar                                              | None                                     |
	| L     | phosphor-lighting     | 1.12.2-0.2.7       | [磷] phosphor-forge-mc1.12.2-0.2.7-universal.jar        | None                                     |

	Loaded coremods (and transformers): 
PatcherPlugin (AdvSolarPatch-1.2.1.jar)
  mods.su5ed.advsolarpatch.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
PhosphorFMLLoadingPlugin ([磷] phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

Running on CatServer with the transformer `thecodex6824.thaumicaugmentation.core.transformer.TransformerSweepingEdgeCheck` disabled.

**Comment by TheCodex6824** [comment]
Your Botania is somehow not making an API class available, which should never happen. I checked that version of Botania from curseforge and everything seemed fine. If you open your version of Botania as a zip file, is there a file at `vazkii/botania/api/item/IPhantomInkable.class`? You don't have to open it, just confirm if it is in your copy or not.

**Comment by Taskeren** [comment]
The class file do exists

**Comment by Taskeren** [comment]
Resolved with the latest Botania. Thanks for the help!

**Comment by Luicuelo** [comment]
I have downloaded the latest version of curseforge and it has been fixed. I'm pretty sure that the file I had before was also from curseforge, at some point they fixed a bug and they didn't put a different version number on it.
