### ISSUE TITLE
Repeated output of unknown error in the background log of the Catserver server

### ISSUE THREAD

**Issue by TryHarder-L** [TheCodex6824/ThaumicAugmentation#326]
[17:19:10] [Server thread/ERROR] [FML]: Cannot Hotload Dim: 3
java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:185) ~[DimensionManager.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:278) [DimensionManager.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1063) [MinecraftServer.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:305) [FMLOutboundHandler$OutboundTarget$9.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:379) [FMLOutboundHandler.class:git-CatServer-1.12.2-dae70adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) [MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) [MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) [DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) [AbstractChannel.class:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:295) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-dae70adc]
	at thecodex6824.thaumicaugmentation.common.event.EntityEventHandler.onLivingEquipmentChange(EntityEventHandler.java:149) [EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EntityEventHandler_onLivingEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2472) [vp.class:?]
	at net.minecraft.entity.item.EntityArmorStand.func_70071_h_(EntityArmorStand.java:744) [abz.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[17:19:10] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:305) ~[FMLOutboundHandler$OutboundTarget$9.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:379) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-dae70adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[AbstractChannel.class:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:295) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-dae70adc]
	at thecodex6824.thaumicaugmentation.common.event.EntityEventHandler.onLivingEquipmentChange(EntityEventHandler.java:149) [EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EntityEventHandler_onLivingEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2472) [vp.class:?]
	at net.minecraft.entity.item.EntityArmorStand.func_70071_h_(EntityArmorStand.java:744) [abz.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[17:19:10] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:305) ~[FMLOutboundHandler$OutboundTarget$9.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:379) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-dae70adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[AbstractChannel.class:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:295) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-dae70adc]
	at thecodex6824.thaumicaugmentation.common.event.EntityEventHandler.onLivingEquipmentChange(EntityEventHandler.java:149) [EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EntityEventHandler_onLivingEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2472) [vp.class:?]
	at net.minecraft.entity.item.EntityArmorStand.func_70071_h_(EntityArmorStand.java:744) [abz.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[17:19:10] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:305) ~[FMLOutboundHandler$OutboundTarget$9.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:379) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-dae70adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[AbstractChannel.class:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:295) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-dae70adc]
	at thecodex6824.thaumicaugmentation.common.event.EntityEventHandler.onLivingEquipmentChange(EntityEventHandler.java:149) [EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EntityEventHandler_onLivingEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2472) [vp.class:?]
	at net.minecraft.entity.item.EntityArmorStand.func_70071_h_(EntityArmorStand.java:744) [abz.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[17:19:10] [Server thread/WARN] [io.netty.channel.embedded.EmbeddedChannel]: More than one exception was raised. Will report only the first one and log others.
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$9.selectNetworks(FMLOutboundHandler.java:305) ~[FMLOutboundHandler$OutboundTarget$9.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:379) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-dae70adc]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[AbstractChannel.class:4.1.24.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(SimpleNetworkWrapper.java:295) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-dae70adc]
	at thecodex6824.thaumicaugmentation.common.event.EntityEventHandler.onLivingEquipmentChange(EntityEventHandler.java:149) [EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EntityEventHandler_onLivingEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) [?:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2472) [vp.class:?]
	at net.minecraft.entity.item.EntityArmorStand.func_70071_h_(EntityArmorStand.java:744) [abz.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by TryHarder-L** [comment]
This is the Mods in the server
![image](https://user-images.githubusercontent.com/50231875/206843247-5d945537-af51-44f8-a45d-37347d0cd0b6.png)

**Comment by TheCodex6824** [comment]
The most I can tell from your log is that some entity is saying it is in dimension 3, but that dimension doesn't exist. There's a chance that some mod/plugin is using that as a dummy value for some reason, but regardless this is a very bizarre thing to encounter.
