### ISSUE TITLE
Crash: Placing something over Rustic's slabs causing `ClassCastException: EnumBlockHalf cannot be cast to Integer`

### ISSUE THREAD

**Issue by Krutoy242** [TheCodex6824/ThaumicAugmentation#335]
Placing slabs over slabs added by mod [Rustic](https://www.curseforge.com/minecraft/mc-mods/rustic) causing MC crash

```less
Caused by: java.lang.ClassCastException: net.minecraft.block.BlockSlab$EnumBlockHalf cannot be cast to java.lang.Integer
    at java.lang.Integer.compareTo(Integer.java:52)
    at thecodex6824.thaumicaugmentation.common.internal.TAHooksCommon.isCompatibleSlab(TAHooksCommon.java:129)
    at thecodex6824.thaumicaugmentation.common.internal.TAHooksCommon.checkWardSlab(TAHooksCommon.java:136)
    at net.minecraft.item.ItemSlab.onItemUse(ItemSlab.java:49)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
```

Right click on this screenshot would cause crash:

![image](https://user-images.githubusercontent.com/936618/228204216-d6f412b4-b521-4b27-b622-cad7d763f625.png)

- ThaumicAugmentation-1.12.2-2.1.9
- Rustic-1.1.7
- Java 1.8.0_362

[debug-1.log.gz](https://github.com/TheCodex6824/ThaumicAugmentation/files/11086817/debug-1.log.gz)

**Comment by TheCodex6824** [comment]
Fixed version should be available soon (TM)
