### ISSUE TITLE
Ticking Exception after exploding rift jar

### ISSUE THREAD

**Issue by rougedarkdragon** [TheCodex6824/ThaumicAugmentation#343]
So when I read that destroying a rift jar chaotically releases a rift, I didn't think it would be this chaotic...
Anyway, here's the crash report. I'm pretty sure it was this mod rather than regular thaumcraft because it happened after I exploded a rift jar.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  iceandfire (iceandfire-1.9.1-1.12.2 (2).jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (1).jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/19/23 12:52 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:386)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:162)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:255)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:386)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:162)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:255)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: New Worldtesttttt
	All players: 1 total; [EntityPlayerMP['RoyalDirtgon'/27225, l='New Worldtesttttt', x=196.17, y=74.67, z=-359.57]]
	Chunk stats: ServerChunkCache: 902 Drop: 0
	Level seed: 352600952414866440
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-52,64,256), Chunk: (at 12,4,0 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 28619 game time, 422619 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 140481 (now: false), thunder time: 122790 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1744075136 bytes (1663 MB) / 2785017856 bytes (2656 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_F5 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version           | Source                                         | Signature                                |
	|:------ |:--------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                   | 9.42              | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | damageindicatorsmod   | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1 (1).jar      | None                                     |
	| LCHIJA | attributefix          | 1.0.10            | AttributeFix-1.12.2-1.0.10.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles               | 1.5.2             | Baubles-1.12-1.5.2 (1).jar                     | None                                     |
	| LCHIJA | bloodmoon             | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31 (1).jar                  | None                                     |
	| LCHIJA | jei                   | 4.16.1.301        | jei_1.12.2-4.16.1.301 (1).jar                  | None                                     |
	| LCHIJA | chisel                | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45 (1).jar               | None                                     |
	| LCHIJA | enchdesc              | 1.1.20            | EnchantmentDescriptions-1.12.2-1.1.20.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | llibrary              | 1.7.20            | llibrary-1.7.20-1.12.2 (2).jar                 | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.9.1             | iceandfire-1.9.1-1.12.2 (2).jar                | None                                     |
	| LCHIJA | eyeofdragons          | 0.0.1             | eyeofdragons-0.0.2 (1).jar                     | None                                     |
	| LCHIJA | mod_lavacow           | 1.3.3             | Fish's+Undead+Rising-1.3.3.jar                 | None                                     |
	| LCHIJA | mca                   | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                 | None                                     |
	| LCHIJA | mowziesmobs           | 1.5.8             | mowziesmobs-1.5.8.jar                          | None                                     |
	| LCHIJA | naturescompass        | 1.8.5             | NaturesCompass-1.12.2-1.8.5 (1).jar            | None                                     |
	| LCHIJA | netherportalfix       | 5.3.17            | NetherPortalFix_1.12.1-5.3.17 (1).jar          | None                                     |
	| LCHIJA | spartanweaponry       | 1.4.1             | SpartanWeaponry-1.12.2-1.4.1.jar               | None                                     |
	| LCHIJA | spartanfire           | 0.08              | spartanfire-0.08.jar                           | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26 (1).jar           | None                                     |
	| LCHIJA | spartanshields        | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar                | None                                     |
	| LCHIJA | spartanweaponryarcana | beta 1.0.3        | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar    | None                                     |
	| LCHIJA | stg                   | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCHIJA | thaumicaugmentation   | 1.12.2-2.1.7      | ThaumicAugmentation-1.12.2-2.1.7.jar           | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | tcinventoryscan       | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10 (1).jar | None                                     |
	| LCHIJA | thaumicjei            | 1.6.0             | ThaumicJEI-1.12.2-1.6.0-27 (1).jar             | None                                     |
	| LCHIJA | waystones             | 4.1.0             | Waystones_1.12.2-4.1.0 (1).jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
iceandfire (iceandfire-1.9.1-1.12.2 (2).jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['RoyalDirtgon'/27225, l='New Worldtesttttt', x=196.17, y=74.67, z=-359.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13497 Compatibility Profile Context 23.20.822.1024
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by rougedarkdragon** [comment]
whoops, i wasn't using the most recent version. that's probably why this happened

**Comment by TheCodex6824** [comment]
If it stopped happening for you after updating that's good, but I'm not sure that will fix it. This crash is probably very rare if it's what I think it is, but if it happens again, let me know. Were you doing anything odd when it happened, or do it near unloaded chunks or something.

**Comment by rougedarkdragon** [comment]
I don't think so. I actually never tested it again in the most recent version so I don't know if it still happens. If I have time and remember I'll try to recreate it.
