### ISSUE TITLE
HBM's crash with Thaumic Augmentation

### ISSUE THREAD

**Issue by Lemvern** [TheCodex6824/ThaumicAugmentation#394]
I have been having a crash with HBM's Nuclear Tech Mod - Extended Edition, error occurs when I click shift to see more information on any of the gas masks equipped with filter, do you have any idea if this has any solution? Thanks in advance, have a nice day. 

Crash report:
<html>
<body>

java.lang.NullPointerException: Rendering screen
--
9 | at thecodex6824.thaumicaugmentation.common.research.ScanEntityWithPeacefulFallback.checkThing(ScanEntityWithPeacefulFallback.java:42)
10 | at thaumcraft.api.research.ScanningManager.isThingStillScannable(ScanningManager.java:91)
11 | at thaumcraft.client.lib.events.RenderEventHandler.oldresearch$shouldRenderAspects(RenderEventHandler.java:1680)
12 | at thaumcraft.client.lib.events.RenderEventHandler.handler$bcd000$tooltipEventInjection1(RenderEventHandler.java:1625)
13 | at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java)
14 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
15 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
16 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
17 | at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
18 | at com.hbm.handler.ArmorUtil.addGasMaskTooltip(ArmorUtil.java:482)
19 | at com.hbm.items.gear.ArmorGasMask.addInformation(ArmorGasMask.java:185)
20 | at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
21 | at net.minecraft.client.gui.GuiScreen.getItemToolTip(GuiScreen.java:143)
22 | at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:137)
23 | at net.minecraft.client.gui.inventory.GuiContainerCreative.renderToolTip(GuiContainerCreative.java:737)
24 | at net.minecraft.client.gui.inventory.GuiContainer.renderHoveredToolTip(GuiContainer.java:175)
25 | at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:684)
26 | at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
27 | at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
28 | at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
29 | at net.minecraft.client.Minecraft.run(Minecraft.java:5114)
30 | at net.minecraft.client.main.Main.main(SourceFile:123)
31 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
32 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
33 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
34 | at java.lang.reflect.Method.invoke(Method.java:498)
35 | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
36 | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
37 |  
38 | No Mixin Metadata is found in the Stacktrace.

</body>
</html>java.lang.NullPointerException: Rendering screen
    at thecodex6824.thaumicaugmentation.common.research.ScanEntityWithPeacefulFallback.checkThing(ScanEntityWithPeacefulFallback.java:42)
    at thaumcraft.api.research.ScanningManager.isThingStillScannable(ScanningManager.java:[9](https://mclo.gs/YRf3JE6#L9)1)
    at thaumcraft.client.lib.events.RenderEventHandler.oldresearch$shouldRenderAspects(RenderEventHandler.java:1680)
    at thaumcraft.client.lib.events.RenderEventHandler.handler$bcd000$tooltipEventInjection1(RenderEventHandler.java:1625)
    at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
    at com.hbm.handler.ArmorUtil.addGasMaskTooltip(ArmorUtil.java:482)
    at com.hbm.items.gear.ArmorGasMask.addInformation(ArmorGasMask.java:185)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
    at net.minecraft.client.gui.GuiScreen.getItemToolTip(GuiScreen.java:143)
    at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:137)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.renderToolTip(GuiContainerCreative.java:737)
    at net.minecraft.client.gui.inventory.GuiContainer.renderHoveredToolTip(GuiContainer.java:175)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:684)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:[11](https://mclo.gs/YRf3JE6#L11)24)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5114)
    at net.minecraft.client.main.Main.main(SourceFile:[12](https://mclo.gs/YRf3JE6#L12)3)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:[13](https://mclo.gs/YRf3JE6#L13)5)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

No Mixin Metadata is found in the Stacktrace.

**Comment by TheCodex6824** [comment]
This was probably fixed by #391 / is related to #390, but I still need to get a bugfix update out. I'm hoping to do that ASAP because it's been long overdue.
