### ISSUE TITLE
seal copier doesn't work on server

### ISSUE THREAD

**Issue by jdratlif** [TheCodex6824/ThaumicAugmentation#60]
When I try to use the seal copier on a server, nothing happens and I get a Java error on the console. It works fine in single player mode.

`[19:04:08] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at thecodex6824.thaumicaugmentation.common.item.ItemSealCopier.onItemUseFirst(ItemSealCopier.java:74) ~[ItemSealCopier.class:?]
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:439) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
`

**Comment by TheCodex6824** [comment]
Yeah this is another thing I fixed in dev but didn't push an update for yet as I was hoping the next major content update would have been finished by now. I'll probably be preparing another patch update today or tomorrow to address this and some other issues that popped up.

**Comment by TheCodex6824** [comment]
I ended up getting the update done for today, this should be fixed in it.

**Comment by jdratlif** [comment]
That is fantastic news. Thanks. I'll be testing it out later today.
