### ISSUE TITLE
Crash on World Startup

### ISSUE THREAD

**Issue by TheTennessee** [TheCodex6824/ThaumicAugmentation#68]
I was working on testing this mod on a test server in creative, and upon trying to log back into it I have found that I am completely locked out of that world. I get a crash on world startup without fail every time now, locking me out of that world. Here's the crash report:

`---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2020-04-30 17:17:59 EDT
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ta_enabled, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:water, properties=[level]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at thecodex6824.thaumicaugmentation.common.tile.TileVisRegenerator.update(TileVisRegenerator.java:97)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbo000(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by TheCodex6824** [comment]
I'm sorry it took me so long to get back to you, I was somewhat busy lately. I was hoping to not have to release any more updates for 1.1 as I'm getting semi-close to at least getting an alpha of 1.2 ready, but I can't leave something like this in for an indeterminate amount of time. I'll probably have a bugfix ready later today.

**Comment by TheCodex6824** [comment]
Update should be [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2954346) once it passes review
